# This is the configuration used to check the rubocop source code.
# See details for the settings below here: http://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop

# to create the todo file, run this in root directory: rubocop --auto-gen-config
# inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'config/**/*'
  TargetRubyVersion: 2.3.3

# ================================
# Lint
# ================================

Lint/UnusedBlockArgument:
  Exclude:
    - 'config/unicorn.rb'

# ================================
# Metrics
# ================================

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# ================================
# Style
# ================================

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

# ================================
# Style
# ================================

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

# new ones:

Style/IdenticalConditionalBranches:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false
  EnforcedStyle: space

Layout/TrailingEmptyLines:
  Enabled: false
  # EnforcedStyle: final_blank_line
  # EnforcedStyle: final_newline

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Lint/LiteralAsCondition:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false
